### ISSUE TITLE
Improve experiment type selector on the coins screen after demo

### ISSUE THREAD

**Issue by jbphet** [phetsims/quantum-measurement#10]
The quick-to-implement version of the experiment type selector is okay for the June 27 2024 demo, but it would be nice to make it more closely match the spec.  This will require adding some options to radio buttons, specifically the ability to specify different background colors for different buttons.

**Comment by arouinfar** [comment]
Discussed in the 9/10/24 design meeting. We decided to continue with a RadioButtonGroup, and there is no need to create a new component that looks like the original mockups.
