### ISSUE TITLE
Incorrect rounding for alpha and beta values in Quantum State

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/quantum-measurement#23]
In Quantum State, when P(⬆)=P(⬇)=0.5, a and b should be equal, but are 0.705 and 0.709. And neither of those square to 0.5

![image](https://github.com/user-attachments/assets/15df596c-e8cd-4b11-9b44-1d255b482844)

**Comment by jbphet** [comment]
@AgustinVallejo and I worked on this today and committed a solution.  Closing.
