### ISSUE TITLE
Changes to titles of Probability sliders

### ISSUE THREAD

**Issue by arouinfar** [phetsims/quantum-measurement#24]
Here's what the Probability sliders currently look like on the Coins screen:
![image](https://github.com/user-attachments/assets/dcc12039-ef6c-4203-b1f5-39600d6bf7b8)
![image](https://github.com/user-attachments/assets/aa77ddc0-2542-44ef-980e-655e880c65b7)

In the 09/05/24 design meeting, we decided to update the titles of these sliders to be more consistent across the classical/quantum scenes:

- [x] Probability P(H)
- [x] Probability P(T)
- [x] Probability P(↑) = |ɑ|<sup>2</sup>
- [x] Probability P(↓) = |β|<sup>2</sup>

Additional notes:
* We want to keep the same color-coding currently in use.
* The "Probability of Heads" language doesn't work well for the Quantum scene, where we would need to say something like "Probability of ↑, P(↑) = |ɑ|<sup>2</sup>. This is why we settled on a shorter label.
* Further discussion is needed to determine if we will transition from Heads/Tails to ♥️/★, but that doesn't affect the format of the slider title, only the character used.

**Comment by AgustinVallejo** [comment]
This is done, now H and T are ♥ and ⭐, and live in the strings file, so they could potentially be translated or modified from a single place in the code.
