### ISSUE TITLE
Use "Classical" instead of "Physical" when referring to non-quantum coin

### ISSUE THREAD

**Issue by arouinfar** [phetsims/quantum-measurement#26]
One of our collaborators provided this feedback:
> Instead of “Physical Coin” and “Quantum Coin” – what about “Classical Coin”, because quantum “coins” are also physical. 

We discussed in the 9/4/24 design meeting, and agreed with this suggestion. "Classical" is the term typically used to contrast against "quantum" in a physics context, so we think it's an appropriate choice.

**Comment by jbphet** [comment]
I've changed the names of all the classes, variables, tandems, etc. from "physical" to "classical".  I've also updated the comments and the implementation-notes document.  I think we're good to go here - closing.
