### ISSUE TITLE
Quantum Coin: change default probability to P(up)=1

### ISSUE THREAD

**Issue by arouinfar** [phetsims/quantum-measurement#31]
In the 9/10/24 design meeting, we decided to change the default configuration of the quantum coin to P(up)=1. 

Due to the changes proposed in #28, any mixed state will result in neither basis state button being selected. The current default is an 80/20 mix, and it feels odd for neither button to be selected by default. The original motivation for the default being an 80/20 mix was that a superposition has a more interesting outcome in the experiment mode. However, students may naturally set up a superposition before their first (or second) experiment, which we'll look for in interviews.

For now, let's use P(up)=1 as the default configuration of the quantum coin.

**Comment by AgustinVallejo** [comment]
This was done as part of #28. Closing
