### ISSUE TITLE
Support PhET-iO State in skipped items

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/quantum-measurement#32]
During https://github.com/phetsims/quantum-measurement/issues/29 we had to set `phetioState: false` for some elements, and left TODO's to address it. They now point to this issue.

**Comment by jbphet** [comment]
I've removed the TODO for `CoinsExperimentSceneModel` because I believe that all the subitems that compose it are either serialized or don't change after construction, so there is no need for any additional state handling for this type.

**Comment by jbphet** [comment]
I've done a bit more thought and investigation on this and am making the decision to just remove the TODOs and leave `phetioState` set to `false` for now.  I think correct serialization will fall out naturally from completing the implementation of the two-state system code in https://github.com/phetsims/quantum-measurement/issues/36.  Closing.
