### ISSUE TITLE
lint-everything is failing on CT and is calling out this sim

### ISSUE THREAD

**Issue by jbphet** [phetsims/quantum-measurement#6]
There is currently a lint failure on CT, and it is referencing this sim.  Here's a screenshot:

![image](https://github.com/phetsims/quantum-measurement/assets/3082831/d2519b8c-d82f-4b1e-bde0-b701efe08443)

I looked at the tsconfig.ts file, and there was a redundant entry for this sim, but removing it didn't seem to make the problem go away.  The `grunt lint-everything` task runs fine for me locally, as does the basic `grunt lint`.  This makes it seem like the problem is caused by CT having some out-of-date data or that I missed some configuration thing when I set up the repo.  At any rate, I could use some help getting this fixed up.

**Comment by jbphet** [comment]
@zepumph volunteered over Slack to take a look.

**Comment by zepumph** [comment]
Thanks for creating. I'll take a look.

**Comment by zepumph** [comment]
Ha. I'm unsure what the issue was, but I went onto sparky and deleted `chipper/eslint/cache/` and now it is working nicely. Thanks for reporting.
