### ISSUE TITLE
Implement performance optimizations for the "Many Photons" scene of the "Photons" screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/quantum-measurement#62]
The "Many Photons" scene on the "Photons" screen depicts a high number of moving photons.  Animations with lots of individual nodes are computationally and graphically intensive, and it may be necessary to do some optimizations to get adequate performance on all supported devices.

Before implementing any of these optimizations, we should make sure they are needed.  I talked with @Nancy-Salpepi about doing some profiling on a Chromebook, since she has one available, and she is up for it.  Let's test the most recent dev version at https://phet-dev.colorado.edu/html/quantum-measurement/1.0.0-dev.8/phet/quantum-measurement_all_phet.html, use the `profiler` query parameter, and record roughly the average frames-per-second value at 200 photons/second.  Here's a screenshot from the same test on my computer:

![image](https://github.com/user-attachments/assets/0e6d3e41-fb4c-401a-b023-b09555f3bbfc)

**Comment by jbphet** [comment]
For my own reference, running this test in a full screen incognito Chrome window on my extra monitor on my home office setup gave a result of about 43 FPS.  On my main screen it was pretty steady at 30 FPS.  So yeah, it looks like there is room for improvement.

Assigning to @Nancy-Salpepi to get some data on her Chromebook.

**Comment by Nancy-Salpepi** [comment]
On the Lenovo 2e Chromebook, it was 15/16 FPS.
On the iPad 9th generation, it was 25/26 FPS.

**Comment by jbphet** [comment]
I've implemented sprites for the photons and profiled the performance on both my main and external monitors, and both showed a solid 60 FPS, which is essentially full speed.

I did some memory profiling to see if frequent allocations of `Vector2` instances for the photon motion was causing significant garbage collections, since these can cause pauses in the rendering.  I didn't see any signs of problems, so I am going to hold off on implementing any optimizations in this area until we do another round of performance measurements.

@Nancy-Salpepi - Please profile again on the same two devices using https://phet-dev.colorado.edu/html/quantum-measurement/1.0.0-dev.9/phet/quantum-measurement_all_phet.html?profiler and let me know what you see.

**Comment by Nancy-Salpepi** [comment]
Looks much improved!
iPad 9th gen: 60 FPS
Lenovo 2e Chromebook: 59/60 FPS

**Comment by jbphet** [comment]
Awesome.  I think we'll call that good then, at least for now.  Closing.
